Se incorpora endpoint de cotizaciones para ser consumido desde el front
ggoffredo/TTIP-Grupo1-2s2022 pull request #34
Opened 2022-10-11 02:03 UTC by ggoffredo

2022-10-11 02:03 UTC, ggoffredo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Todos los llamados deben hacerse a través del back](https://trello.com/c/tyfV4AXa/63-todos-los-llamados-deben-hacerse-a-trav%C3%A9s-del-back)

2022-10-11 12:03 UTC, jcvincenti requested changes

2022-10-11 12:03 UTC, jcvincenti commented on lfm-front/src/components/CustomTables/CompraDolaresTable.jsx
> +        return Number(value).toFixed(2).replace(".", ",")
O de última hacerlo en el service de cotizaciones y tenerlo en un solo lugar.

2022-10-11 12:03 UTC, jcvincenti commented on src/main/kotlin/ar/edu/unq/ttip/llegarafindemes/services/CotizacionesService.kt
> +                (it["casa"] as LinkedHashMap<String,String>)!!["nombre"] ?: "",
Por que tanto condicional? Si el problema son otros dolares que puede que no tengan alguna key, podemos filtrar primero y después mapear.

2022-10-14 21:49 UTC, jcvincenti approved these changes

2022-10-14 21:49 UTC, merged