Plazo fijo csv
ggoffredo/TTIP-Grupo1-2s2022 pull request #5
Opened 2022-09-04 18:44 UTC by ggoffredo

2022-09-04 18:44 UTC, ggoffredo commented
![](https://github.trello.services/images/mini-trello-icon.png) [(8) Extracción de información de plazos fijos disponibles por el BCRA](https://trello.com/c/CumxXFL2/28-8-extracci%C3%B3n-de-informaci%C3%B3n-de-plazos-fijos-disponibles-por-el-bcra)

2022-09-04 19:11 UTC, jcvincenti requested changes

2022-09-04 19:11 UTC, jcvincenti commented on src/main/kotlin/ar/edu/unq/ttip/llegarafindemes/services/BCRAService.kt
> +                codigoEntidad = csvRecord.get(0),
Imagino que por el formato que tiene el excel, no debe haber otra manera que obtener los valores por medio de IDs (aunque es muy poco feliz)

2022-09-04 19:11 UTC, jcvincenti commented on src/main/kotlin/ar/edu/unq/ttip/llegarafindemes/jobs/PlazoFijoJob.kt
> +        println("Updating Plazos fijo")
Cambiaría los println por logger.info de última.

`private val logger = LoggerFactory.getLogger(PlazoFijoJob::class.java)`

2022-09-04 19:11 UTC, jcvincenti commented on src/main/kotlin/ar/edu/unq/ttip/llegarafindemes/jobs/PlazoFijoJob.kt
> +    @Scheduled(cron = "0 0/2 * * * ?")
Ojo que quedó cada 2 minutos (si no me equivoco). Podría ser
```suggestion
    @Scheduled(cron = "0 0 0 * * ?")
```
Si no le pifio, eso debería ser todos los días a la media noche.

2022-09-08 17:39 UTC, jcvincenti approved these changes

2022-09-08 17:39 UTC, merged